# Lab | Web Scraping

Welcome to the IMDb Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the vast sea of data available on IMDb, one of the largest online databases of movie, TV, and celebrity information. As budding data scientists and business analysts, you have been tasked to scrape a specific subset of data from IMDb to assist film production companies in understanding the landscape of highly-rated movies in a defined time period. Your insights will potentially influence the making of the next netflix movie!

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The entertainment industry, being no exception, utilizes data analytics to comprehend market trends, audience preferences, and the performance of films based on various parameters such as director, genre, stars involved, etc. IMDb stands as a goldmine of such data, offering intricate details of almost every movie ever made.

**Task**

Your task is to create a Python script using `BeautifulSoup` and `pandas` to scrape IMDb movie data based on user ratings and release dates. This script should be able to filter movies with ratings above a certain threshold and within a specified date range.

**Expected Outcome**

- A function named `scrape_imdb` that takes four parameters: `title_type`,`user_rating`, `start_date`, and `end_date`.
- The function should return a DataFrame with the following columns:
  - **Movie Nr**: The number representing the movie’s position in the list.  xxxxxxxxxxx
  - **Title**: The title of the movie.                     xxxxxxxxxxxxxxxxxxxxxx
  - **Year**: The year the movie was released.           xxxxxxxxxxxxxxxxxxx
  - **Rating**: The IMDb rating of the movie.            xxxxxxxxxxxxxxxxxxxx
  - **Runtime (min)**: The duration of the movie in minutes.   xxxxxxxxxxxxxxxxx
  - **Genre**: The genre of the movie.
  - **Description**: A brief description of the movie.                  xxxxxxxxxxxxxx
  - **Director**: The director of the movie.
  - **Stars**: The main stars of the movie.
  - **Votes**: The number of votes the movie received.          XXXXXXXXXXXXXXX
  - **Gross ($M)**: The gross earnings of the movie in millions of USD.

You will execute this script to scrape data for movies with the Title Type `Feature Film` that have a user rating of `7.5 and above` and were released between `January 1, 1990, and December 31, 1992`.

Remember to experiment with different title types, dates and ratings to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [IMDb Advanced Search](https://www.imdb.com/search/title/)

**Hint**

Your first mission is to familiarize yourself with the IMDb advanced search page. Head over to [IMDb advanced search](https://www.imdb.com/search/title/) and input the following parameters, keeping all other fields to their default values or blank:

- **Title Type**: Feature film
- **Release date**: From 1990 to 1992 (Note: You don't need to specify the day and month)
- **User Rating**: 7.5 to -

Upon searching, you'll land on a page showcasing a list of movies, each displaying vital details such as the title, release year, and crew information. Your task is to scrape this treasure trove of data.

Carefully examine the resulting URL and construct your own URL to include all the necessary parameters for filtering the movies.


---

**Best of luck! Immerse yourself in the world of movies and may the data be with you!**

**Important note**:

In the fast-changing online world, websites often get updates and make changes. When you try this lab, the IMDb website might be different from what we expect.

If you run into problems because of these changes, like new rules or things that stop you from getting data, don't worry! Instead, get creative.

You can choose another website that interests you and is good for scraping data. Websites like Wikipedia or The New York Times are good options. The main goal is still the same: get useful data and learn how to scrape it from a website that you find interesting. It's a chance to practice your web scraping skills and explore a source of information you like.

In [3]:
def scrape_imdb(title_type, user_rating, start_date, end_date):
    import pandas as pd
    from bs4 import BeautifulSoup
    import requests
    
    
    url = f"https://www.imdb.com/search/title/?title_type={title_type}&release_date={start_date},{end_date}&user_rating={user_rating}"
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36'}
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, "html.parser")
    
    
    title_element = soup.find_all("h3", class_ ="ipc-title__text")
    titles_lists = [i.get_text().split(".") for i in title_element]

    # 1
    nr = [i[0] for i in titles_lists[:25]]
    
    # 2
    titles = [i[1].strip() for i in titles_lists[:25]]
    
    # 3
    year_element = soup.find_all("span", class_ = "sc-300a8231-7 eaXxft dli-title-metadata-item")
    year_lists = [i.get_text() for i in year_element if i.get_text() in ['1990','1991','1992'] ]
    
    # 4
    rating_element = soup.find_all('span', class_="ipc-rating-star--rating")
    rating_lists = [i.get_text() for i in rating_element]
    
    # 5
    runtime_element = soup.find_all("span", class_ = "sc-300a8231-7 eaXxft dli-title-metadata-item")
    runtime_lists = [i.get_text() for i in runtime_element]
    runtime = runtime_lists[1:74:3]
    
    # 6
    description_elements = soup.find_all("div", class_ = 'ipc-html-content-inner-div')
    description = [i.get_text() for i in description_elements]
    
    # 7
    votes_element = soup.find_all("span", class_ = "ipc-rating-star--voteCount")
    votes = [i.get_text() for i in votes_element]
    vote = [i.replace("\xa0(","").replace(")","") for i in votes]
    
    # Formatting the dataframe
    df = pd.DataFrame({"Number": nr, "Title": titles,"Year":year_lists ,"Rating": rating_lists,"Voting":vote, "Description": description})

    return df

In [8]:
scrape_imdb("feature", 8.2, "1990-01-01", "1992-12-31")

,Number,Title,Year,Rating,Voting,Description
0,1,GoodFellas - Drei Jahrzehnte in der Mafia,1990,8.7,1.3M,The story of Henry Hill and his life in the ma...
1,2,Das Schweigen der Lämmer,1991,8.6,1.6M,A young F.B.I. cadet must receive the help of ...
2,3,Terminator 2: Tag der Abrechnung,1991,8.6,1.2M,"A cyborg, identical to the one who failed to k..."
3,4,Reservoir Dogs - Wilde Hunde,1992,8.3,1.1M,When a simple jewelry heist goes horribly wron...
4,5,Erbarmungslos,1992,8.2,448K,Retired Old West gunslinger Will Munny relucta...
5,6,Close Up,1990,8.2,24K,"The true story of Hossain Sabzian, a cinephile..."
6,7,Baraka,1992,8.5,42K,A collection of expertly photographed scenes o...
7,8,Paris brennt,1990,8.2,19K,A chronicle of New York's drag scene in the 19...
8,9,Ein Sommer zum Verlieben,1991,8.2,14K,"Based on a true story, primarily on a conflict..."
9,10,Mi nismo andjeli,1992,8.3,9.7K,Angel and the devil fight for the soul of a Be...
10,11,Michael Madana Kama Rajan,1990,8.5,5.3K,"A comedy of errors with identical quadruplets,..."
11,12,Thalapathi,1991,8.5,14K,An orphan named Surya raised in a slum befrien...
12,13,Thevar Magan,1992,8.7,8.4K,The urbane son of a village chieftain struggle...
13,14,Madar,1990,8.5,5.2K,"How a mother acts in the hardest parts of her,..."
14,15,Kilukkam,1991,8.7,4.9K,A tourist guide in Ooty shelters a mentally un...
15,16,Godfather,1991,8.6,4.4K,"Since Anjooran hates women, his sons remain un..."
16,17,Anjali,1990,8.2,3.2K,"After a few years, Chitra learns that her chil..."
17,18,Ek Doctor Ki Maut,1990,8.3,1.6K,After years of painstaking research at the cos...
18,19,Sandesham,1991,9.0,5.6K,A satire on contemporary Kerala politics where...
19,20,Sadayam,1992,8.4,1.1K,Sadayam follows the final days of a condemned ...
20,21,Amaram,1991,8.3,3.3K,An uneducated fisherman wants his daughter to ...
21,22,Yoddha,1992,8.4,5K,Fate brings a young man from rural Kerala to b...
22,23,Tetoviranje,1991,8.5,931,"After a quarrel with his wife, a man leaves th..."
23,24,Bingbong: The Vincent Crisologo Story,1991,8.2,37,"Bingbong, son of Ilocos Sur Governor, terroriz..."
24,25,El-Kit Kat,1991,8.2,2.8K,Sheikh Hosny is a blind man who lives with his...